/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coe318.lab7;
/**
 * Represents a voltage source in an electrical circuit.
 * 
 * <p>
 * A voltage source generates a specific voltage and is connected to two nodes in the circuit.
 * Each voltage source is assigned a unique identifier.
 * </p>
 * 
 * @author atabl
 */
public class VoltageSrc {
    
    /**
     * Voltage generated by the voltage source.
     */
    private double voltage;
    
    /**
     * Node representing one end of the voltage source.
     */
    private Node node1;
    
    /**
     * Node representing the other end of the voltage source.
     */
    private Node node2;
    
    /**
     * Static variable to keep track of the next available identifier for a voltage source.
     */
    private static int ID = 1;
    
    /**
     * Unique identifier for each individual voltage source.
     */
    private int individual_ID;
    
    /**
     * Constructs a VoltageSrc with the specified voltage and connected nodes.
     * 
     * @param voltage The voltage generated by the voltage source.
     * @param node1 The first node to which the voltage source is connected.
     * @param node2 The second node to which the voltage source is connected.
     * 
     * @throws IllegalArgumentException If node1 is equal to node2 (invalid node connection).
     */
    public VoltageSrc(double voltage, Node node1, Node node2){
        this.voltage = voltage;
        
        if(node1 != node2){
            this.node1 = node1;
            this.node2 = node2;
        }else{
            throw new IllegalArgumentException("Invalid node connection!");
        }
        
        individual_ID = ID;
        ID++;
    }
    
    /**
     * Gets the nodes to which the voltage source is connected.
     * 
     * @return An array containing the two nodes connected to the voltage source.
     */
    public Node[] getNodes(){
        Node[] n = {this.node1, this.node2};
        return n;
    }
    
    /**
     * Returns a string representation of the voltage source.
     * 
     * @return A string containing the voltage source's unique identifier,
     *         connected nodes, voltage value, and the type of source (DC).
     */
    @Override
    public String toString(){
        return "V" + this.individual_ID + " " + this.node1.toString() + " " + this.node2.toString() + " DC " + this.voltage;
    }
    
}
